# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoella Razili
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yoella Razili is an Israeli-born artist who lives and works in Los Angeles. 
  Her work belongs to the non-objective art movement and spans a range of 
  media including found materials and paint.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
